#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if yunohost service status "$app" >/dev/null 2>&1; then
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
